// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return [];
      });
  var setLetters = match[1];
  var letters = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setDragged = match$1[1];
  var dragged = match$1[0];
  var match$2 = React.useState(function () {
        return Core__Array.make(651, undefined);
      });
  var setGrid = match$2[1];
  var grid = match$2[0];
  var match$3 = React.useState(function () {
        return true;
      });
  var setLoading = match$3[1];
  var match$4 = React.useState(function () {
        
      });
  var setHintWord = match$4[1];
  var hintWord = match$4[0];
  var indexToCoord = function (index) {
    var row = index / 21 | 0;
    var col = index % 21;
    var centerRow = 15;
    var centerCol = 10;
    var x = col - centerCol | 0;
    var y = centerRow - row | 0;
    return [
            x,
            y
          ];
  };
  var sendBoardToServer = async function (grid) {
    try {
      var boardMap = Core__Array.reduce(Core__Array.filterMap(grid.map(function (item, index) {
                    if (item === undefined) {
                      return ;
                    }
                    var match = indexToCoord(index);
                    var key = match[0].toString() + "," + match[1].toString();
                    return [
                            key,
                            item[0]
                          ];
                  }), (function (x) {
                  return x;
                })), {}, (function (dict, param) {
              dict[param[0]] = param[1];
              return dict;
            }));
      var json_data = JSON.stringify(boardMap);
      var options = {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: json_data
      };
      var response = await fetch("http://localhost:8080/validate", options);
      var json = await response.json();
      var status = response.status;
      if (status >= 200 && status < 300) {
        window.alert("✓ Board is valid!");
      } else {
        var msg = Core__JSON.Decode.string(json);
        if (msg !== undefined) {
          window.alert("✗ " + msg);
        } else {
          window.alert("✗ Validation failed");
        }
      }
      console.log("Board submitted successfully");
      return ;
    }
    catch (exn){
      window.alert("✗ Failed to validate board");
      return ;
    }
  };
  React.useEffect((function () {
          var fetchTiles = async function () {
            try {
              var response = await fetch("http://localhost:8080/get_random_tiles?count=21");
              var json = await response.json();
              var arr = Core__JSON.Decode.array(json);
              var tiles = arr !== undefined ? Core__Array.filterMap(arr, Core__JSON.Decode.string) : [];
              var tilesWithIds = tiles.map(function (letter, idx) {
                    return [
                            letter,
                            idx.toString()
                          ];
                  });
              setLetters(function (param) {
                    return tilesWithIds;
                  });
              return setLoading(function (param) {
                          return false;
                        });
            }
            catch (exn){
              console.log("Failed to fetch tiles");
              return setLoading(function (param) {
                          return false;
                        });
            }
          };
          fetchTiles();
        }), []);
  var fetchMoreTiles = async function () {
    try {
      var response = await fetch("http://localhost:8080/get_random_tiles?count=3");
      var json = await response.json();
      var arr = Core__JSON.Decode.array(json);
      var tiles = arr !== undefined ? Core__Array.filterMap(arr, Core__JSON.Decode.string) : [];
      return setLetters(function (prev) {
                  var maxId = Core__Array.reduce(prev, 0, (function (max, param) {
                          var idNum = Core__Option.getOr(Core__Int.fromString(param[1], undefined), 0);
                          if (max > idNum) {
                            return max;
                          } else {
                            return idNum;
                          }
                        }));
                  var newTiles = tiles.map(function (letter, idx) {
                        return [
                                letter,
                                ((maxId + idx | 0) + 1 | 0).toString()
                              ];
                      });
                  return prev.concat(newTiles);
                });
    }
    catch (exn){
      console.log("Failed to fetch more tiles");
      return ;
    }
  };
  var handleHint = async function () {
    try {
      var response = await fetch("http://localhost:8080/hint");
      var json = await response.json();
      var w = Core__JSON.Decode.string(json);
      var word = w !== undefined ? w : "";
      return setHintWord(function (param) {
                  return word;
                });
    }
    catch (exn){
      console.log("Failed to fetch hint");
      return setHintWord(function (param) {
                  
                });
    }
  };
  var handleDrop = function (index) {
    return function (e) {
      e.preventDefault();
      if (dragged === undefined) {
        return ;
      }
      var id = dragged[1];
      var letter = dragged[0];
      setGrid(function (prevGrid) {
            var newGrid = prevGrid.slice();
            newGrid[index] = [
              letter,
              id
            ];
            return newGrid;
          });
      setLetters(function (prevLetters) {
            return prevLetters.filter(function (param) {
                        return param[1] !== id;
                      });
          });
      setDragged(function (param) {
            
          });
    };
  };
  var handleDragOver = function (e) {
    e.preventDefault();
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Available Letters",
                                      className: "text-2xl font-bold"
                                    }),
                                hintWord !== undefined ? JsxRuntime.jsx("p", {
                                        children: "Hint: " + hintWord,
                                        className: "text-sm text-blue-600 mt-1"
                                      }) : null,
                                JsxRuntime.jsx("p", {
                                      children: "Please place your first letter in the middle of the board (on the blue grid cell)",
                                      className: "text-sm text-blue-600 mt-1"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Hint",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600",
                                      onClick: (function (param) {
                                          handleHint();
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Dump",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600",
                                      onClick: (function (param) {
                                          fetchMoreTiles();
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Validate",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600",
                                      onClick: (function (param) {
                                          sendBoardToServer(grid);
                                        })
                                    })
                              ],
                              className: "flex gap-2"
                            })
                      ],
                      className: "flex items-center justify-between mb-4"
                    }),
                JsxRuntime.jsx("div", {
                      children: letters.length > 0 ? letters.map(function (letter, index) {
                              var actual_letter = letter[0];
                              return JsxRuntime.jsx("div", {
                                          children: actual_letter,
                                          className: "cursor-move px-4 py-2 bg-blue-300 rounded shadow-md text-xl font-bold select-none hover:bg-blue-400",
                                          draggable: true,
                                          onDragStart: (function (e) {
                                              setDragged(function (param) {
                                                    return letter;
                                                  });
                                            })
                                        }, actual_letter + "-" + index.toString());
                            }) : JsxRuntime.jsx("div", {
                              children: "No letters available",
                              className: "text-gray-500"
                            }),
                      className: "flex gap-3 mb-8 flex-wrap min-h-20 p-4 bg-gray-100 rounded overflow-visible"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Grid",
                      className: "text-2xl font-bold mb-4"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: grid.map(function (item, index) {
                                  var centerIndex = 325;
                                  var isCenter = index === centerIndex;
                                  var bgColor = isCenter ? "bg-blue-200" : "bg-white";
                                  return JsxRuntime.jsx("div", {
                                              children: item !== undefined ? JsxRuntime.jsx("div", {
                                                      children: item[0],
                                                      className: "cursor-pointer w-full h-full flex items-center justify-center bg-green-400 text-sm font-bold select-none hover:bg-red-400",
                                                      title: "Click to remove",
                                                      onClick: (function (param) {
                                                          var id = item[1];
                                                          var letter = item[0];
                                                          setGrid(function (prevGrid) {
                                                                var newGrid = prevGrid.slice();
                                                                newGrid[index] = undefined;
                                                                return newGrid;
                                                              });
                                                          setLetters(function (prevLetters) {
                                                                return prevLetters.concat([[
                                                                              letter,
                                                                              id
                                                                            ]]);
                                                              });
                                                        })
                                                    }) : null,
                                              className: "w-8 h-8 border border-gray-300 flex items-center justify-center hover:bg-gray-50 " + bgColor,
                                              onDragOver: handleDragOver,
                                              onDrop: handleDrop(index)
                                            }, index.toString());
                                }),
                            style: {
                              display: "grid",
                              gridTemplateColumns: "repeat(21, 2rem)"
                            }
                          }),
                      className: "inline-block border border-gray-400"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Drag letters to the grid. Click on placed letters to remove them.",
                      className: "mt-4 text-sm text-gray-600"
                    })
              ],
              className: "max-w-4xl mx-auto p-8 pt-120 overflow-auto"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
