// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

function App(props) {
  var initialLetters = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U"
  ];
  var match = React.useState(function () {
        return initialLetters;
      });
  var setLetters = match[1];
  var letters = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setDragged = match$1[1];
  var dragged = match$1[0];
  var match$2 = React.useState(function () {
        return Core__Array.make(25, undefined);
      });
  var setGrid = match$2[1];
  var handleDrop = function (index) {
    return function (e) {
      e.preventDefault();
      if (dragged !== undefined) {
        setGrid(function (prevGrid) {
              var newGrid = prevGrid.slice();
              newGrid[index] = dragged;
              return newGrid;
            });
        setLetters(function (prevLetters) {
              return prevLetters.filter(function (l) {
                          return l !== dragged;
                        });
            });
        return setDragged(function (param) {
                    
                  });
      }
      
    };
  };
  var handleDragOver = function (e) {
    e.preventDefault();
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Available Letters",
                      className: "text-2xl font-bold mb-4"
                    }),
                JsxRuntime.jsx("div", {
                      children: letters.length > 0 ? letters.map(function (letter) {
                              return JsxRuntime.jsx("div", {
                                          children: letter,
                                          className: "cursor-move px-4 py-2 bg-blue-300 rounded shadow-md text-xl font-bold select-none hover:bg-blue-400",
                                          draggable: true,
                                          onDragStart: (function (e) {
                                              setDragged(function (param) {
                                                    return letter;
                                                  });
                                            })
                                        }, letter);
                            }) : JsxRuntime.jsx("div", {
                              children: "No letters available",
                              className: "text-gray-500"
                            }),
                      className: "flex gap-3 mb-8 flex-wrap min-h-20 p-4 bg-gray-100 rounded"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Grid",
                      className: "text-2xl font-bold mb-4"
                    }),
                JsxRuntime.jsx("div", {
                      children: match$2[0].map(function (item, index) {
                            return JsxRuntime.jsx("div", {
                                        children: item !== undefined ? JsxRuntime.jsx("div", {
                                                children: item,
                                                className: "cursor-pointer px-4 py-2 bg-green-400 rounded shadow-md text-xl font-bold select-none hover:bg-red-400",
                                                title: "Click to remove",
                                                onClick: (function (param) {
                                                    setGrid(function (prevGrid) {
                                                          var newGrid = prevGrid.slice();
                                                          newGrid[index] = undefined;
                                                          return newGrid;
                                                        });
                                                    setLetters(function (prevLetters) {
                                                          return prevLetters.concat([item]);
                                                        });
                                                  })
                                              }) : null,
                                        className: "w-20 h-20 border-2 border-dashed border-gray-400 rounded flex items-center justify-center bg-white hover:bg-gray-50",
                                        onDragOver: handleDragOver,
                                        onDrop: handleDrop(index)
                                      }, index.toString());
                          }),
                      className: "grid grid-cols-5 gap-2"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Drag letters to the grid. Click on placed letters to remove them.",
                      className: "mt-4 text-sm text-gray-600"
                    })
              ],
              className: "max-w-4xl mx-auto p-8"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
